apiVersion: apps/v1
kind: Deployment
metadata:
  name: podset-operator3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podset-operator3
  template:
    metadata:
      labels:
        name: podset-operator3
    spec:
      serviceAccountName: podset-operator3
      containers:
        - name: podset-operator3
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - podset-operator3
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podset-operator3"
